#!/usr/bin/env python3

import rospy

import message_filters
from geometry_msgs.msg import TwistStamped, TwistWithCovarianceStamped

rospy.init_node("message_filter")

odom_pub = rospy.Publisher(
    "wheel_odom_with_covariance", TwistWithCovarianceStamped, queue_size=5)
odom_msg = TwistWithCovarianceStamped()

wheel_odom_cov = rospy.get_param("~wheel_odom_covariance_diagonal")

for i in range(6):
    odom_msg.twist.covariance[i*7] = wheel_odom_cov[i]

def odom_callback(odom):
    odom_msg.header.stamp = odom.header.stamp
    odom_msg.twist.twist = odom.twist

    odom_pub.publish(odom_msg)

odom_sub = rospy.Subscriber("wheel_odom", TwistStamped, odom_callback)

rospy.spin()
